In [2]:
# Paso 1: Cargamos librerías para el análisis exploratorio de los datos.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

In [98]:
#Paso1: Cargamos todos los archivos, para realizar el análisis exploratorio de los datos.

agendamiento = pd.read_excel("agendamiento.xlsx")
gestantes = pd.read_excel("Gestantes.xlsx")
medicamentos = pd.read_excel("Medicamentos.xlsx")
rcv = pd.read_excel("RCV.xlsx")
rips = pd.read_excel("RIPS.xlsx") 
fechas = pd.read_excel("DimCalendario_Colombia_2026_enriquecido.xlsx")

In [ ]:
#El objetivo del proyecto de esta sección es construir las variables necesarias para la contrucción 
# de un modelo predictivo de inasistencia.

Las variables que debemos construir son las siguientes: 

Historial de asistencia	Tasa histórica de inasistencia del paciente
Historial de asistencia	Estado de la última cita
Historial de asistencia	Número de citas previas asistidas o inasistidas
Agendamiento	Tiempo entre agendamiento y cita
Agendamiento	Día de la semana de la cita
Agendamiento	Mes o estacionalidad de la cita
Agendamiento	Hora de la cita (Agenda)
Agendamiento	Tipo de cita (primera vez, control o derivada)
Agendamiento	Especialidad o servicio
Sociodemográfica	Edad (Agenda)
Sociodemográfica	Sexo (Agenda)
Sociodemográfica	Tipo de aseguramiento o régimen (Agendamiento: Nivel usuario // Tipo usuario)
Sociodemográfica	Municipio, comuna o zona de residencia
Media-alta	Por confirmar (dirección del paciente)
Clínica	Condición crónica o número de diagnósticos	1 / 3 (alto impacto donde se midió)	Media-alta	Sí (población de crónicos)
Clínica	Gestante
Clínica	Número de medicamentos o polifarmacia
Clínica	Hospitalización reciente
Clínica	Cirugía ambulatoria

Solución: Necesitamos explorar los archivos con el fin de validar la mejor manera de consturir las variables.

In [8]:
#Paso 1.1: Exploración de agendamiento.xlsx
print(agendamiento.shape)
display(agendamiento.head());
print(agendamiento.info());
print(agendamiento.columns)

#Análisis: la columnas son las siguientes: 
# (['Id_med_paciente'( Join paciente), 'sexo'(variable de interés), 'nivel_usr'(Variable régimen), 'tipo_usuario' (variable régimen), 'edad (variable edad)',
#       'nombre_cnt', 'turno' (Variable interés ), 'fecha_cita', 'fecha_asig', 'control',
#       'especialidad_cita', 'procedimiento_especifico', 'dx_ppal'],

#especialidad_cita: vamos a probar inicialmente con todas las especialidades. 
# pero se va a eliminar columna dx ppal por dara lackeage y además inicialmente vamos a borrar procedimiento especifico
#por sospecha de colinealidad con procedimiento específico.

#debemos calcular una nueva columna que es tiempo en solicitud de cita y fecha cita.


#llenar vacíos en fecha asignada 
# debemos cambios tipos de datos

(576252, 13)

,Id_med_paciente,sexo,nivel_usr,tipo_usuario,edad,nombre_cnt,turno,fecha_cita,fecha_asig,control,especialidad_cita,procedimiento_especifico,dx_ppal
0,1533808,Femenino,1,COTIZANTE,28,P-VIVA 1A IPS CENTRO,08:15:00,2026-03-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA,TOMA NO QUIRURGICA DE MUESTRA DE TEJIDO VAGINAL,NaN
1,1797221,Femenino,1,COTIZANTE,30,P-VIVA 1A IPS LAURELES,15:00:00,2026-06-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA,TOMA NO QUIRURGICA DE MUESTRA DE TEJIDO VAGINAL,NaN
2,2252142,Femenino,1,COTIZANTE,59,P-VIVA 1A IPS LAURELES,14:15:00,2026-06-25,2026-03-26,NaN,PROMOCION Y PREVENCION - ENFERMERIA,TOMA NO QUIRURGICA DE MUESTRA DE TEJIDO VAGINAL,NaN
3,2267785,Femenino,1,BENEFICIARIO,55,P-VIVA 1A IPS LAURELES,16:15:00,2026-06-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA,TOMA NO QUIRURGICA DE MUESTRA DE TEJIDO VAGINAL,NaN
4,2444476,Femenino,1,COTIZANTE,45,P-VIVA 1A IPS LAURELES,16:45:00,2026-06-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA,TOMA NO QUIRURGICA DE MUESTRA DE TEJIDO VAGINAL,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576252 entries, 0 to 576251
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Id_med_paciente           576252 non-null  int64
 1   sexo                      576252 non-null  object
 2   nivel_usr                 576252 non-null  int64
 3   tipo_usuario              576252 non-null  object
 4   edad                      576252 non-null  int64
 5   nombre_cnt                576252 non-null  object
 6   turno                     576252 non-null  object
 7   fecha_cita                576252 non-null  datetime64[ns]
 8   fecha_asig                576239 non-null  datetime64[ns]
 9   control                   267350 non-null  object
 10  especialidad_cita         568700 non-null  object
 11  procedimiento_especifico  152760 non-null  object
 12  dx_ppal                   299255 non-null  object
dtypes: datetime64[ns](2), int64(3), object(8)
memory usage: 57.2+ MB
None
Index(['Id_med_paciente', 'sexo', 'nivel_usr', 'tipo_usuario', 'edad',
       'nombre_cnt', 'turno', 'fecha_cita', 'fecha_asig', 'control',
       'especialidad_cita', 'procedimiento_especifico', 'dx_ppal'],
      dtype='object')

In [41]:
# Ver todos los valores únicos de la columna
display(agendamiento["especialidad_cita"].dropna().unique().tolist())

['PROMOCION Y PREVENCION - ENFERMERIA',
 'MEDICINA GENERAL',
 'AUXILIAR EN SALUD ORAL',
 'ODONTOLOGIA',
 'GINECOLOGIA Y OBSTETRICIA',
 'OBSTETRICIA - GINECOLOGO',
 'NUTRICIONISTA',
 'PSICOLOGIA',
 'PEDIATRIA',
 'ENDODONCIA',
 'MEDICINA INTERNA',
 'CIRUGIA ORAL',
 'HTA/Cronico - Medico',
 'DERMATOLOGIA',
 'NEFROLOGIA',
 'GINECOLOGIA',
 'PSIQUIATRIA',
 'MEDICINA FAMILIAR',
 'ENDOCRINOLOGIA',
 'ORTOPEDIA Y TRAUMATOLOGIA',
 'NEUROLOGIA',
 'MEDICINA FISICA Y REHABILITACION',
 'HIGIENE ORAL',
 'Control Prenatal - Medico',
 'Cronico - Psicologia',
 'NEUMOLOGIA',
 'Salud Mental - Md Gral',
 'Salud Publica - Medico',
 'OBSTETRICIA - Ginecologo',
 'Control Prenatal - Enfermeria',
 'CIRUGIA GENERAL',
 'Juventud - Md Gral',
 'FISIOTERAPIA',
 'TERAPISTA RESPIRATORIO',
 'DOLOR Y CUIDADOS PALIATIVOS',
 'CIRUGIA MAXILOFACIAL',
 'Adultez - Md Gral',
 'Primera Infancia - Md Gral',
 'Adolescencia - Enf',
 'Adolescencia - Odont',
 'Infancia - Enf',
 'Planificacion Familiar - Enfermeria',
 'Vejez - Md Gral',
 'Vejez - Enf',
 'Salud Publica - Enfermeria',
 'HTA/Cronico - Enfermeria',
 'Diabetes - Medico',
 'FONOAUDIOLOGIA',
 'Primera Infancia - Enf',
 'Primera Infancia - Odont',
 'Juventud - Odont',
 'Adultez - Odont',
 'OTORRINOLARINGOLOGIA',
 'Adultez - Enf',
 'Atencion a la Familia - Odont',
 'Nefroproteccion - Medico',
 'TERAPIA OCUPACIONAL',
 'Infancia - Md Gral',
 'Infancia - Odont',
 'Cronico - Nutricionista',
 'Adolescencia - Md Gral',
 'Planificacion Familiar - Medico',
 'ENFERMERIA',
 'Juventud - Enf',
 'Vejez - Odont',
 'PAC MEDICINA INTERNA',
 'Atencion a la Familia - Md Gral',
 'PAC ORTOPEDIA Y TRAUMATOLOGIA',
 'PAC DERMATOLOGIA',
 'Primera Infancia - Pediatria',
 'PAC PSIQUIATRIA',
 'Cronico - Medico Internista',
 'PAC CIRUGIA GENERAL',
 'Infancia - Pediatria',
 'PAC PEDIATRIA',
 'CIRUGIA ORAL Y MAXILOFACIAL']

In [42]:
# Valores únicos de dx_ppal y número de registros por valor
display(agendamiento["especialidad_cita"].value_counts(dropna=False))

especialidad_cita
MEDICINA GENERAL                       221162
ODONTOLOGIA                             60580
HTA/Cronico - Medico                    41349
FISIOTERAPIA                            37212
PROMOCION Y PREVENCION - ENFERMERIA     29395
                                        ...
Atencion a la Familia - Md Gral             4
Cronico - Medico Internista                 1
PAC CIRUGIA GENERAL                         1
PAC PSIQUIATRIA                             1
PAC PEDIATRIA                               1
Name: count, Length: 77, dtype: int64

In [44]:
#Paso 1.1: Elijo las columnas de interés agendamiento.xlsx

columns = [
    'Id_med_paciente', 'sexo', 'nivel_usr', 'tipo_usuario',
    'edad', 'nombre_cnt', 'turno', 'fecha_cita', 'fecha_asig',
    'control', 'especialidad_cita'
]

agendamiento = agendamiento.loc[:, columns]

In [45]:
agendamiento

,Id_med_paciente,sexo,nivel_usr,tipo_usuario,edad,nombre_cnt,turno,fecha_cita,fecha_asig,control,especialidad_cita
0,1533808,Femenino,1,COTIZANTE,28,P-VIVA 1A IPS CENTRO,08:15:00,2026-03-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA
1,1797221,Femenino,1,COTIZANTE,30,P-VIVA 1A IPS LAURELES,15:00:00,2026-06-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA
2,2252142,Femenino,1,COTIZANTE,59,P-VIVA 1A IPS LAURELES,14:15:00,2026-06-25,2026-03-26,NaN,PROMOCION Y PREVENCION - ENFERMERIA
3,2267785,Femenino,1,BENEFICIARIO,55,P-VIVA 1A IPS LAURELES,16:15:00,2026-06-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA
4,2444476,Femenino,1,COTIZANTE,45,P-VIVA 1A IPS LAURELES,16:45:00,2026-06-25,2026-03-24,NaN,PROMOCION Y PREVENCION - ENFERMERIA
...,...,...,...,...,...,...,...,...,...,...,...
576247,3782725,Femenino,1,BENEFICIARIO,17,VIVA 1A IPS VILLAMARIA,17:00:00,2026-06-12,2026-03-12,NaN,NUTRICIONISTA
576248,3782725,Femenino,1,BENEFICIARIO,17,VIVA 1A IPS VILLAMARIA,16:45:00,2026-06-16,2026-05-16,X,PSICOLOGIA
576249,3782725,Femenino,1,BENEFICIARIO,17,VIVA 1A IPS VILLAMARIA,14:30:00,2026-09-12,2026-06-12,X,NUTRICIONISTA
576250,3785789,Femenino,1,BENEFICIARIO,16,VIVA 1A IPS SA - SEDE VILLAMARIA,13:20:00,2026-04-11,2026-03-30,NaN,MEDICINA GENERAL
576251,3785789,Femenino,1,BENEFICIARIO,16,VIVA 1A IPS VILLAMARIA,09:40:00,2026-05-05,2026-05-04,NaN,MEDICINA GENERAL

In [52]:
#Paso 2: Cambio los tipo de datos de las columnas
#Id_med_paciente: Str // sexo: Str // nivel_usr: int // tipo_usuario: str // Edad: Int //
#nombre_cnt: Str // Turno: Hora (llevar a rango hora 7, 8, 9) // Fecha cita y fecha_asig : Datatime
# Control: X=1, Missing Value:0 //especialidad_cita: str.

# Paso 2: Cambio los tipo de datos de las columnas
# Id_med_paciente: Str // sexo: Str // nivel_usr: int // tipo_usuario: str // Edad: Int //
# nombre_cnt: Str // Turno: Hora (llevar a rango hora 7, 8, 9) // Fecha cita y fecha_asig : Datatime
# Control: X=1, Missing Value:0 // especialidad_cita: str.

agendamiento["Id_med_paciente"] = agendamiento["Id_med_paciente"].astype(str)
agendamiento["sexo"] = agendamiento["sexo"].astype(str)
agendamiento["nivel_usr"] = agendamiento["nivel_usr"].astype("Int64")
agendamiento["tipo_usuario"] = agendamiento["tipo_usuario"].astype(str)
agendamiento["edad"] = agendamiento["edad"].astype("Int64")
agendamiento["nombre_cnt"] = agendamiento["nombre_cnt"].astype(str)
agendamiento["fecha_cita"] = pd.to_datetime(agendamiento["fecha_cita"], errors="coerce")
agendamiento["fecha_asig"] = pd.to_datetime(agendamiento["fecha_asig"], errors="coerce")

# Turno: convertir texto de hora a un valor numérico por franja horaria
agendamiento["turno"] = pd.to_datetime(agendamiento["turno"], format="%H:%M", errors="coerce")
minutos = agendamiento["turno"].dt.hour * 60 + agendamiento["turno"].dt.minute
agendamiento['turno_sin'] = np.sin(2 * np.pi * minutos / 1440)
agendamiento['turno_cos'] = np.cos(2 * np.pi * minutos / 1440)

# Control: X = 1, faltante = 0
agendamiento["control"] = agendamiento["control"].map({"X": 1}).fillna(0).astype(int)

# Especialidad: texto
agendamiento["especialidad_cita"] = agendamiento["especialidad_cita"].astype(str)

In [55]:
#Construyo una columna de lead time, en donde identifico el tiempo transcurrido entre fecha_asign hasta fecha_cita
agendamiento["lead_time"] = (
    agendamiento["fecha_cita"] - agendamiento["fecha_asig"]
).dt.days

In [56]:
agendamiento

,Id_med_paciente,sexo,nivel_usr,tipo_usuario,edad,nombre_cnt,turno,fecha_cita,fecha_asig,control,especialidad_cita,minutos,turno_sin,turno_cos,lead_time
0,1533808,Femenino,1,COTIZANTE,28,P-VIVA 1A IPS CENTRO,NaT,2026-03-25,2026-03-24,0,PROMOCION Y PREVENCION - ENFERMERIA,NaN,NaN,NaN,1.0
1,1797221,Femenino,1,COTIZANTE,30,P-VIVA 1A IPS LAURELES,NaT,2026-06-25,2026-03-24,0,PROMOCION Y PREVENCION - ENFERMERIA,NaN,NaN,NaN,93.0
2,2252142,Femenino,1,COTIZANTE,59,P-VIVA 1A IPS LAURELES,NaT,2026-06-25,2026-03-26,0,PROMOCION Y PREVENCION - ENFERMERIA,NaN,NaN,NaN,91.0
3,2267785,Femenino,1,BENEFICIARIO,55,P-VIVA 1A IPS LAURELES,NaT,2026-06-25,2026-03-24,0,PROMOCION Y PREVENCION - ENFERMERIA,NaN,NaN,NaN,93.0
4,2444476,Femenino,1,COTIZANTE,45,P-VIVA 1A IPS LAURELES,NaT,2026-06-25,2026-03-24,0,PROMOCION Y PREVENCION - ENFERMERIA,NaN,NaN,NaN,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576247,3782725,Femenino,1,BENEFICIARIO,17,VIVA 1A IPS VILLAMARIA,NaT,2026-06-12,2026-03-12,0,NUTRICIONISTA,NaN,NaN,NaN,92.0
576248,3782725,Femenino,1,BENEFICIARIO,17,VIVA 1A IPS VILLAMARIA,NaT,2026-06-16,2026-05-16,0,PSICOLOGIA,NaN,NaN,NaN,31.0
576249,3782725,Femenino,1,BENEFICIARIO,17,VIVA 1A IPS VILLAMARIA,NaT,2026-09-12,2026-06-12,0,NUTRICIONISTA,NaN,NaN,NaN,92.0
576250,3785789,Femenino,1,BENEFICIARIO,16,VIVA 1A IPS SA - SEDE VILLAMARIA,NaT,2026-04-11,2026-03-30,0,MEDICINA GENERAL,NaN,NaN,NaN,12.0
576251,3785789,Femenino,1,BENEFICIARIO,16,VIVA 1A IPS VILLAMARIA,NaT,2026-05-05,2026-05-04,0,MEDICINA GENERAL,NaN,NaN,NaN,1.0

In [97]:
agendamiento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576252 entries, 0 to 576251
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Id_med_paciente    576252 non-null  object
 1   sexo               576252 non-null  object
 2   nivel_usr          576252 non-null  Int64
 3   tipo_usuario       576252 non-null  object
 4   edad               576252 non-null  Int64
 5   nombre_cnt         576252 non-null  object
 6   turno              0 non-null       datetime64[ns]
 7   fecha_cita         576252 non-null  datetime64[ns]
 8   fecha_asig         576239 non-null  datetime64[ns]
 9   control            576252 non-null  int64
 10  especialidad_cita  576252 non-null  object
 11  minutos            0 non-null       float64
 12  turno_sin          0 non-null       float64
 13  turno_cos          0 non-null       float64
 14  lead_time          576239 non-null  float64
dtypes: Int64(2), datetime64[ns](3), float64(4), int64(1), object(5)
memory usage: 67.0+ MB

In [60]:
#Ahora vamos a revisar el archivo gestantes. 
display(gestantes.shape);
display(gestantes.head(100))

## Es un archivo que contiene a las gestante, pero no es claro el rango en el cual es gestante activa.

(784, 2)

    id_med_paciente        fum
0              3108 2024-07-13
1            514448 2025-10-28
2            718153 2022-01-14
3            797806 2026-03-15
4            800309 2026-02-13
..              ...        ...
95          1158158 2025-11-14
96          1158158 2025-11-24
97          1168453 2025-09-12
98          1168809 2025-07-23
99          1169622 2025-04-05

[100 rows x 2 columns]

In [61]:
#Ahora vamos a revisar el archivo medicamentos. 
display(medicamentos.shape);
display(medicamentos.head(100))

## Es un archivo que contiene los medicamentos formulados durante la consulta, por lo tanto podria abordarse con un conteo de medicamentos que toma "polifarmacia"
# o podría considerarse como datalakage dado que la prescripción se da después de la cita.

(175948, 4)

,id_med_paciente,medicamento,cantidad,fec_orden
0,76022,TIZANIDINA+ACETAMINOFEN 2/350 mg (TABLETA),15,2026-03-25 09:36:43
1,76022,ETORICOXIB 60 mg (TABLETA),14,2026-03-25 09:36:43
2,493091,CARBONATO DE CALCIO + VITAMINA D3 500MG/200UI ...,30,2026-01-08 08:45:53
3,493091,METOPROLOL TARTRATO 50 mg (TABLETA O GRAGEA),60,2026-01-08 08:45:53
4,493091,ATORVASTATINA 40 MG (TABLETA),30,2026-01-08 08:45:53
...,...,...,...,...
95,581562,VITAMINA D3 (COLECALCIFEROL) 2000 UI (CAPSULA ...,30,2026-01-20 17:14:14
96,581562,"APIXABAN 2,5 MG‚ (TABLETA)-(H)",60,2026-01-20 17:14:14
97,581562,BETAHISTINA 24 MG (TABLETA),30,2026-01-20 17:14:14
98,581562,FOLICO ACIDO 1 mg (TABLETA),30,2026-01-20 17:14:14
99,581562,EZETIMIBA + ROSUVASTATINA 10/40 MG (TABLETA),30,2026-01-20 17:14:14

In [63]:
## paso medicamentos: dejamos solo la columna id_med_paciente y medicamento 
medicamentos = medicamentos.loc[:, ["id_med_paciente", "medicamento"]]

In [68]:
#agrupamos por cédula y por número de conteo de medicamentos
medicamentos = (
    medicamentos.groupby("id_med_paciente", as_index=False)["medicamento"]
    .nunique()
    .rename(columns={"medicamento": "numero_medicamentos"})
)

medicamentos.head()

   id_med_paciente  numero_medicamentos
0            36149                    3
1            74787                    2
2            75395                    4
3            76022                    2
4            94611                    5

In [73]:
#revisamos documento rcv
print(rcv.shape)
display(rcv.head(100))
display(rcv.info())

(21003, 3)

    id_med_paciente                     Programa Diabetes
0           1209397         Programa de Diabetes        X
1           1264747         Programa de Diabetes        X
2           1279691         Programa de Diabetes        X
3           1279692     Programa de Hipertension      NaN
4           1279861     Programa de Hipertension      NaN
..              ...                          ...      ...
95          1270178     Programa de Hipertension      NaN
96          1270179         Programa de Diabetes        X
97          1270209         Programa de Diabetes        X
98          1283634     Programa de Hipertension      NaN
99          1283792  Programa de Nefroproteccion      NaN

[100 rows x 3 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21003 entries, 0 to 21002
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_med_paciente  21003 non-null  int64
 1   Programa         20935 non-null  object
 2   Diabetes         6517 non-null   object
dtypes: int64(1), object(2)
memory usage: 492.4+ KB

None

In [78]:
#Llenamos Missing value en programa con Programa de Hipertension, valor que ya se encuentra en la columna# Llenamos los valores faltantes de Programa
rcv["Programa"] = rcv["Programa"].fillna("Programa de Hipertension")

# Columna diabetes cambios valores x=1 y Missing Value=0
# Diabetes: X = 1, valor faltante = 0
rcv["Diabetes"] = rcv["Diabetes"].eq("X").astype(int)

display(rcv)

       id_med_paciente                  Programa  Diabetes
0              1209397      Programa de Diabetes         1
1              1264747      Programa de Diabetes         1
2              1279691      Programa de Diabetes         1
3              1279692  Programa de Hipertension         0
4              1279861  Programa de Hipertension         0
...                ...                       ...       ...
20998          3013289  Programa de Hipertension         0
20999          2966122      Programa de Diabetes         1
21000          2966131  Programa de Hipertension         0
21001          2966145  Programa de Hipertension         0
21002          3013399  Programa de Hipertension         0

[21003 rows x 3 columns]

In [84]:
#quiero ver las categorías de la columna diabetes por cantidad y por porcentaje 
diabetes_counts = rcv["Diabetes"].value_counts().sort_index()
diabetes_pct = rcv["Diabetes"].value_counts(normalize=True).sort_index() * 100

pd.DataFrame({
    "cantidad": diabetes_counts,
    "porcentaje": diabetes_pct
})

          cantidad  porcentaje
Diabetes
0            14486   68.971099
1             6517   31.028901

In [85]:
print(rcv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21003 entries, 0 to 21002
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_med_paciente  21003 non-null  int64
 1   Programa         21003 non-null  object
 2   Diabetes         21003 non-null  int64
dtypes: int64(2), object(1)
memory usage: 492.4+ KB
None

In [88]:
#Revisamos rips 
print(rips.shape)
print(rips.info())
display(rips.head())

(290150, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290150 entries, 0 to 290149
Data columns (total 7 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Id_med_paciente             290150 non-null  int64
 1   fechainicioatencion         290150 non-null  datetime64[ns]
 2   codconsulta                 289953 non-null  float64
 3   codDiagnosticoPrincipal     290150 non-null  object
 4   codDiagnosticoRelacionado1  131873 non-null  object
 5   codDiagnosticoRelacionado2  56710 non-null   object
 6   codDiagnosticoRelacionado3  20956 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 15.5+ MB
None

,Id_med_paciente,fechainicioatencion,codconsulta,codDiagnosticoPrincipal,codDiagnosticoRelacionado1,codDiagnosticoRelacionado2,codDiagnosticoRelacionado3
0,1067579,2026-07-30 10:00:00,890208.0,Z133,NaN,NaN,NaN
1,1067579,2026-02-04 09:25:00,890208.0,R458,Z634,NaN,NaN
2,1067579,2026-03-17 08:49:00,890308.0,R458,Z634,NaN,NaN
3,1067579,2026-05-11 18:40:00,890201.0,J342,S022,NaN,NaN
4,1067579,2026-08-18 07:15:00,890208.0,R458,NaN,NaN,NaN

In [94]:
#dejamos solo las columnas que son de mi interés Id_med_pacoiente, fechainicioatención y codconsulta 
rips = rips.loc[:, ["Id_med_paciente", "fechainicioatencion", "codconsulta"]]

#cambiamos tipo de dato "Id_med_paciente":str, "fechainicioatencion":fecha, "codconsulta":str
# cambiamos tipo de dato "Id_med_paciente":str, "fechainicioatencion":fecha, "codconsulta":int
rips["Id_med_paciente"] = rips["Id_med_paciente"].astype(str)
rips["fechainicioatencion"] = pd.to_datetime(rips["fechainicioatencion"], errors="coerce")
rips["codconsulta"] = rips["codconsulta"].astype(str)

# creamos una nueva columna para todos los valores que dice Asiste
rips["estado_cita"] = "Asiste"

In [96]:
rips.head()

  Id_med_paciente fechainicioatencion codconsulta estado_cita
0         1067579 2026-07-30 10:00:00      890208      Asiste
1         1067579 2026-02-04 09:25:00      890208      Asiste
2         1067579 2026-03-17 08:49:00      890308      Asiste
3         1067579 2026-05-11 18:40:00      890201      Asiste
4         1067579 2026-08-18 07:15:00      890208      Asiste